# Generated by Django 3.0.7 on 2020-09-05 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_type', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=50, null=True, verbose_name='GRN_Type')),
                ('received_store', models.CharField(blank=True, choices=[('Ramnagar', 'Ramnagar'), ('B', 'B'), ('C', 'C')], max_length=50, null=True, verbose_name='Received Store')),
                ('vendor_supplier', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vendor/Supplier')),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='D/C or Invoice No')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='Received Date')),
                ('received_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Received By')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Invoice Date')),
                ('invoice_amount', models.FloatField(blank=True, null=True, verbose_name='Invoice Amount')),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Goods',
                'verbose_name_plural': 'Goods',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(blank=True, choices=[('Ramnagar', 'Ramnagar'), ('B', 'B'), ('C', 'C')], max_length=50, null=True, verbose_name='Store')),
                ('patient', models.CharField(blank=True, max_length=50, null=True, verbose_name='Patien Name')),
                ('referred_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Referred By')),
                ('payment_type', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI')], max_length=50, null=True, verbose_name='Payment Type')),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='Sale_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item Name')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('batch_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Batch ID')),
                ('unit_price', models.FloatField(blank=True, null=True, verbose_name='Unit Price')),
                ('Discount', models.FloatField(blank=True, null=True, verbose_name='Discount')),
                ('gst', models.FloatField(blank=True, null=True, verbose_name='GST(%)')),
                ('sub_total', models.FloatField(blank=True, null=True, verbose_name='Sub Total')),
                ('total_vat', models.FloatField(blank=True, null=True, verbose_name='GST Amount')),
                ('total_amount', models.FloatField(blank=True, null=True, verbose_name='Net_Amount')),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('patiant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharma_app.Sale')),
            ],
            options={
                'verbose_name': 'Sale_Item',
                'verbose_name_plural': 'Sale_Items',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item Name')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('free_quantity', models.IntegerField(blank=True, null=True, verbose_name='Free Quantity')),
                ('batch_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Batch ID')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('sale_price', models.FloatField(blank=True, null=True, verbose_name='Sale Price')),
                ('cost_price', models.FloatField(blank=True, null=True, verbose_name='Cost Price')),
                ('gst', models.FloatField(blank=True, null=True, verbose_name='GST(%)')),
                ('sub_total', models.FloatField(blank=True, null=True, verbose_name='Sub Total')),
                ('gst_amount', models.FloatField(blank=True, null=True, verbose_name='GST Amount')),
                ('remarks', models.CharField(blank=True, max_length=150, null=True, verbose_name='Remarks')),
                ('net_amount', models.FloatField(blank=True, null=True, verbose_name='Net_Amount')),
                ('round_off', models.IntegerField(blank=True, null=True, verbose_name='Round Off')),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('vendor_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharma_app.Goods')),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
            },
        ),
    ]
