# Generated by Django 3.0.7 on 2020-10-30 18:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='user uuid')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField()),
                ('user_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='User Name')),
                ('mobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mobile Number')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user/images', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Doctor Name')),
                ('doctor_age', models.CharField(blank=True, max_length=100, null=True, verbose_name='Age')),
                ('sex', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='FEMALE', max_length=10, verbose_name='Sex')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicines', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Medicine Name')),
            ],
        ),
        migrations.CreateModel(
            name='VendorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_type', models.CharField(blank=True, default='Purchase Received', max_length=50, null=True, verbose_name='GRN_Type')),
                ('received_store', models.CharField(blank=True, default='Ramnagar', max_length=50, null=True, verbose_name='Received Store')),
                ('vendor_supplier', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vendor/Supplier')),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='D/C or Invoice No')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='Received Date')),
                ('received_by', models.CharField(blank=True, choices=[('D. Sujatha', 'D. Sujatha'), ('D. Shantha Rao', 'D. Shantha Rao')], default='D. Sujatha', max_length=50, null=True, verbose_name='Received By')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Invoice Date')),
                ('invoice_amount', models.FloatField(blank=True, null=True, verbose_name='Invoice Amount')),
                ('gst_amount', models.FloatField(blank=True, null=True, verbose_name='GST Amount')),
                ('remarks', models.CharField(blank=True, max_length=150, null=True, verbose_name='Remarks')),
                ('net_amount', models.FloatField(blank=True, null=True, verbose_name='Net_Amount')),
                ('round_off', models.IntegerField(blank=True, null=True, verbose_name='Round Off')),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(blank=True, default='Ramnagar', max_length=50, null=True, verbose_name='Store')),
                ('bill_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bill_No')),
                ('patient', models.CharField(blank=True, max_length=50, null=True, verbose_name='Patien Name')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile Number')),
                ('payment_type', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI'), ('Others', 'Others')], max_length=50, null=True, verbose_name='Payment Type')),
                ('total_vat', models.FloatField(blank=True, null=True, verbose_name='GST Amount')),
                ('net_amount', models.FloatField(blank=True, null=True, verbose_name='Net_Amount')),
                ('total_amount', models.FloatField(blank=True, null=True, verbose_name='Total_Amountt')),
                ('sale_date', models.DateField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('referred_by', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharma_app.DoctorName', verbose_name='Referred By')),
            ],
        ),
        migrations.CreateModel(
            name='PatientCollectedMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item Name')),
                ('quantity', models.CharField(blank=True, max_length=10, null=True, verbose_name='Quantity')),
                ('batch_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Batch ID')),
                ('unit_price', models.FloatField(blank=True, null=True, verbose_name='Unit Price')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('discount', models.FloatField(blank=True, null=True, verbose_name='Discount')),
                ('gst', models.FloatField(blank=True, null=True, verbose_name='GST(%)')),
                ('sub_total', models.FloatField(blank=True, null=True, verbose_name='Sub Total')),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharma_app.PatientInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item Name')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('sale_quantity', models.IntegerField(blank=True, null=True, verbose_name='Sale Quantity')),
                ('free_quantity', models.IntegerField(blank=True, null=True, verbose_name='Free Quantity')),
                ('batch_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Batch ID')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('sale_price', models.FloatField(blank=True, null=True, verbose_name='Sale Price')),
                ('cost_price', models.FloatField(blank=True, null=True, verbose_name='Cost Price')),
                ('gst', models.CharField(blank=True, choices=[('5', '5%'), ('12', '12%'), ('18', '18%')], max_length=50, null=True, verbose_name='GST(%)')),
                ('sub_total', models.FloatField(blank=True, null=True, verbose_name='Sub Total')),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('vendor_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharma_app.VendorInfo')),
            ],
        ),
    ]
