# Generated by Django 3.0.7 on 2020-09-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale_items',
            old_name='Discount',
            new_name='discount',
        ),
    ]
