# Generated by Django 3.0.7 on 2020-10-31 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Vendor Name')),
            ],
        ),
    ]
