# Generated by Django 3.0.7 on 2020-11-03 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_app', '0002_vendorname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='status',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='patientcollectedmedicine',
            old_name='status',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='patientinfo',
            old_name='status',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='vendorinfo',
            old_name='status',
            new_name='is_active',
        ),
    ]
