# Generated by Django 3.0.7 on 2020-09-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_app', '0002_auto_20200905_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='gst_amount',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='net_amount',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='round_off',
        ),
        migrations.AddField(
            model_name='goods',
            name='gst_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='GST Amount'),
        ),
        migrations.AddField(
            model_name='goods',
            name='net_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Net_Amount'),
        ),
        migrations.AddField(
            model_name='goods',
            name='remarks',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='goods',
            name='round_off',
            field=models.IntegerField(blank=True, null=True, verbose_name='Round Off'),
        ),
    ]
