# Generated by Django 3.0.7 on 2020-09-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_app', '0006_auto_20200909_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='bill_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bill_No'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI'), ('Others', 'Others')], max_length=50, null=True, verbose_name='Payment Type'),
        ),
    ]
