# Generated by Django 3.0.7 on 2020-09-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_app', '0007_auto_20200910_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
